# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X5MNue3Q8MTWAYi06ruXH6tSo0PdKewO
"""

import numpy as np

def random_vector():
    while True:                                     # Infinite loop
        base_vector       = np.random.rand(3)       # Three independent random numbers from a uniform distribution in the range (0, 1)
        vector            = 2 * base_vector - 1     # Shift the vector to the range (-1, 1)
        vector_length     = np.linalg.norm(vector)  # Calculate vector length
        if (vector_length) <= 1:                      # Break from the loop if length less than or equal to 1
            break
    normalized_vector     = vector / vector_length  # Normalize vector
    return normalized_vector

size_siml = 100000
#The variable below stores number of points with -1/2 <= z <= 1/2. 
numb_z_req = 0
for i in range(size_siml):
  example_vector = random_vector()
  val_z = example_vector[2]

  if val_z >= -0.5 and val_z <= 0.5:
    numb_z_req += 1
  
# The variables below store the probability values based on simulations  
prob_req_range = numb_z_req / size_siml

print(" The following results are obtained from simulations")
print(f"The probability that -0.5 <= z <= 0.5 from simulations is : {prob_req_range}")

print()
print("The following results are obtained theoretically")
print("The probability that -0.5 <= z <= 0.5 theoretically is : 0.5")
diff_var_z = prob_req_range - 0.5
print(f"The difference between the simulations' and the theoretical values are : {diff_var_z}")